# This workflow will install node dependencies, build the source code and run tests

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install dependencies
      run: npm ci
      working-directory: docs
    - name: Build
      run: npm run build --if-present
      working-directory: docs
